package com.sonicether.soundphysics.eap.emitter;

import com.sonicether.soundphysics.Loggers;
import com.sonicether.soundphysics.eap.EnvironmentProfile;
import net.minecraft.client.Minecraft;
import net.minecraft.core.BlockPos;
import org.lwjgl.openal.AL10;
import org.lwjgl.openal.AL11;

import java.util.*;

/**
 * Manages the full lifecycle of Layer 1 environmental emitters:
 * scanning for candidates, reconciling with the current emitter set,
 * distance-based culling, gain computation, pool allocation, and ticking.
 *
 * <p>Delegates OpenAL source management to {@link EmitterPool} and
 * block scanning to {@link EmitterScanner}. Procedural audio buffers
 * are lazily generated by {@link ProceduralBufferFactory}.
<<<<<<< ours
 *
 * <p>Integrates triggered (sample-based) emitters via {@link SampleEmitterScheduler},
 * environment-driven gain modulation via {@link EnvironmentConditions},
 * and Felix Hess frog chorus emergence model.
 */
public final class EmitterManager {

    private static final int POOL_SIZE = 32;
    private static final int RESCAN_INTERVAL_TICKS = 40;
    private static final int SAMPLE_RATE = 44100;

    // Per-category caps for continuous (looping) emitters to prevent any single category
    // from flooding the pool. Triggered emitters allocate on-demand and aren't capped here.
    private static final Map<EmitterCategory, Integer> MAX_CONTINUOUS_PER_CATEGORY = Map.of(
            EmitterCategory.WIND_LEAF, 6,
            EmitterCategory.WIND_GRASS, 4,
            EmitterCategory.WIND_WHISTLE, 2,
            EmitterCategory.WATER_FLOW, 6,
            EmitterCategory.LAVA, 4,
            EmitterCategory.CAVE_DRONE, 3
    );
=======
 */
public final class EmitterManager {

    private static final int POOL_SIZE = 16;
    private static final int RESCAN_INTERVAL_TICKS = 100;
>>>>>>> theirs

    private final EmitterPool pool;
    private final EmitterScanner scanner;
    private final ProceduralBufferFactory bufferFactory;
<<<<<<< ours
<<<<<<< ours
=======
>>>>>>> theirs
    private final SamplePoolLoader samplePoolLoader = new SamplePoolLoader();
    private final SampleEmitterScheduler scheduler = new SampleEmitterScheduler();
    private final Random triggeredRng = new Random();
=======
>>>>>>> theirs
    private final Map<Long, Emitter> emittersByPos = new HashMap<>();

    private boolean enabled = true;
    private float masterGain = 0.5f;
    private float density = 0.75f;
<<<<<<< ours
    private int ticksSinceRescan = RESCAN_INTERVAL_TICKS;
    private boolean scanInProgress = false;

    private EnvironmentConditions conditions;
    private java.util.Map<EmitterCategory, Boolean> categoryEnabled = new java.util.EnumMap<>(EmitterCategory.class);
    private float faunaVolume = 0.5f;
    private boolean underwater = false;
<<<<<<< ours
    private float lastScanX, lastScanY, lastScanZ;
=======
>>>>>>> theirs

=======
    private int ticksSinceRescan = 0;
    private boolean scanInProgress = false;

>>>>>>> theirs
    public EmitterManager() {
        this.pool = new EmitterPool(POOL_SIZE);
        this.scanner = new EmitterScanner();
        this.bufferFactory = new ProceduralBufferFactory();
    }

    /**
<<<<<<< ours
     * Main per-tick update with environment conditions.
     * Performs incremental scanning, reconciliation, distance-based culling,
     * condition-aware gain updates, allocation, pool tick, and triggered emitter scheduling.
     */
    public void tick(Minecraft minecraft, EnvironmentProfile profile, EnvironmentConditions conditions) {
        this.conditions = conditions;

=======
     * Main per-tick update. Performs incremental scanning, reconciliation,
     * distance-based culling, gain updates, allocation, and pool tick.
     */
    public void tick(Minecraft minecraft, EnvironmentProfile profile) {
>>>>>>> theirs
        if (!enabled || minecraft.level == null || minecraft.player == null) {
            return;
        }

<<<<<<< ours
<<<<<<< ours
<<<<<<< ours
        samplePoolLoader.loadAll();
        pool.setSamplePoolLoader(samplePoolLoader);

        this.underwater = minecraft.player.isUnderWater();

=======
>>>>>>> theirs
=======
=======
        samplePoolLoader.loadAll();
        pool.setSamplePoolLoader(samplePoolLoader);

>>>>>>> theirs
        this.underwater = minecraft.player.isUnderWater();

>>>>>>> theirs
        long currentTick = minecraft.level.getGameTime();
        float playerX = (float) minecraft.player.getX();
        float playerY = (float) minecraft.player.getY();
        float playerZ = (float) minecraft.player.getZ();

<<<<<<< ours
        // Force immediate rescan if player teleported (moved > 8 blocks since last scan)
        float dx = playerX - lastScanX;
        float dy = playerY - lastScanY;
        float dz = playerZ - lastScanZ;
        if (dx * dx + dy * dy + dz * dz > 64f) { // 8 blocks squared
            ticksSinceRescan = RESCAN_INTERVAL_TICKS;
        }

=======
>>>>>>> theirs
        // Incremental scan cycle
        ticksSinceRescan++;
        if (!scanInProgress && ticksSinceRescan >= RESCAN_INTERVAL_TICKS) {
            scanner.beginCycle(
                    (int) playerX, (int) playerY, (int) playerZ);
            scanInProgress = true;
            ticksSinceRescan = 0;
<<<<<<< ours
            lastScanX = playerX;
            lastScanY = playerY;
            lastScanZ = playerZ;
=======
>>>>>>> theirs
        }

        if (scanInProgress) {
            boolean done = scanner.tickScan(minecraft.level);
            if (done) {
                scanInProgress = false;
<<<<<<< ours
<<<<<<< ours
                reconcile(scanner.getCandidates(), playerX, playerY, playerZ, conditions);
=======
                reconcile(scanner.getCandidates(), playerX, playerY, playerZ);
>>>>>>> theirs
=======
                reconcile(scanner.getCandidates(), playerX, playerY, playerZ, conditions);
>>>>>>> theirs
            }
        }

        // Cull emitters beyond range
        cull(playerX, playerY, playerZ);

        // Update gains based on distance, wind exposure, and profile
        updateGains(playerX, playerY, playerZ, profile);

<<<<<<< ours
<<<<<<< ours
=======
>>>>>>> theirs
        // Tick pool FIRST (smooth parameters, handle fades, recycle finished sources).
        pool.tick(masterGain, currentTick);

        // Allocate sources for continuous emitters AFTER pool has freed finished slots.
        allocateNewEmitters();

        // Tick triggered (sample-based) emitters — generates and plays one-shot buffers
        tickTriggeredEmitters(currentTick);

        // Rotate sample buffers on continuous sample-based emitters (e.g. WATER_FLOW)
        tickContinuousSampleSwap(triggeredRng);

<<<<<<< ours
        // DEBUG: log active emitter categories every 5 seconds
        if (currentTick % 100 == 0) {
            var catCounts = new java.util.EnumMap<EmitterCategory, int[]>(EmitterCategory.class);
            for (Emitter e : emittersByPos.values()) {
                catCounts.computeIfAbsent(e.category, k -> new int[]{0, 0});
                catCounts.get(e.category)[0]++;
                if (e.active && e.sourceId != 0) {
                    int state = AL10.alGetSourcei(e.sourceId, AL10.AL_SOURCE_STATE);
                    if (state == AL10.AL_PLAYING) catCounts.get(e.category)[1]++;
                }
            }
            StringBuilder sb = new StringBuilder("EMITTER-DEBUG active: ");
            for (var entry : catCounts.entrySet()) {
                int[] c = entry.getValue();
                if (c[1] > 0) sb.append(entry.getKey().name()).append("=").append(c[1]).append("/").append(c[0]).append(" ");
            }
            com.sonicether.soundphysics.Loggers.log(sb.toString());
        }

=======
>>>>>>> theirs
    }

    /**
     * Backward-compatible tick without environment conditions.
     * Delegates to the full tick with null conditions (falls back to profile-only gains).
     */
    public void tick(Minecraft minecraft, EnvironmentProfile profile) {
        tick(minecraft, profile, null);
    }

    /**
     * Ticks all sample-based emitters (iterates emittersByPos, not pool).
     * Sample-based emitters only allocate a pool slot on-demand when triggered,
     * and the slot is returned when playback finishes (AL_STOPPED in pool.tick).
     * This prevents idle triggered emitters from consuming pool slots.
     *
     * Includes Felix Hess eagerness model for frog chorus emergence.
     */
    private void tickTriggeredEmitters(long currentTick) {
        if (conditions == null) return;

        for (Emitter e : emittersByPos.values()) {
            if (!e.category.sampleBased) continue;
<<<<<<< ours
<<<<<<< ours
            if (e.category == EmitterCategory.BAT) continue; // No synthesis for BAT yet
=======
>>>>>>> theirs
=======
            if (e.category == EmitterCategory.BAT) continue; // No synthesis for BAT yet
>>>>>>> theirs
            if (e.targetGain < 0.001f) continue;

            // If currently has a source and is playing, skip
            if (e.active && e.sourceId != 0) {
                int state = AL10.alGetSourcei(e.sourceId, AL10.AL_SOURCE_STATE);
                if (state == AL10.AL_PLAYING) continue;
            }

<<<<<<< ours
            // Frog chorus: Felix Hess eagerness model — eagerness is the SOLE trigger
            // (no scheduler gate, avoids double-gating that caused ~8 min delays)
            if (e.category == EmitterCategory.FROG) {
                e.eagerness += 0.015f;
=======
            // Frog chorus: Felix Hess eagerness model (ticks even without a source)
            if (e.category == EmitterCategory.FROG) {
                e.eagerness += 0.01f;
>>>>>>> theirs

                // Hearing a nearby calling frog boosts eagerness
                for (Emitter other : pool.getActiveEmitters()) {
                    if (other != e && other.category == EmitterCategory.FROG
                            && other.lastCallTick > 0
                            && currentTick - other.lastCallTick < 40
                            && Math.abs(other.blockX - e.blockX) < 20
                            && Math.abs(other.blockZ - e.blockZ) < 20) {
<<<<<<< ours
                        e.eagerness += 0.025f;
=======
                        e.eagerness += 0.02f;
>>>>>>> theirs
                        break;
                    }
                }

                float threshold = 0.8f + triggeredRng.nextFloat() * 0.4f;
                if (e.eagerness < threshold) continue;
                e.eagerness = 0f;
<<<<<<< ours
                // Fall through to allocation and playback — skip scheduler
            } else {
                // All non-frog triggered emitters use the scheduler
                if (!scheduler.shouldTrigger(e, conditions, triggeredRng)) continue;
=======
>>>>>>> theirs
            }

            // --- Trigger fires: allocate source on-demand if needed ---
            if (!e.active || e.sourceId == 0) {
                if (!pool.allocate(e)) continue; // Pool full
                // Set immediate gain (no fade-in for triggered sounds)
                e.currentGain = e.targetGain;
                e.fadeProgress = 1.0f;
            }

            // --- Trigger fires: allocate source on-demand if needed ---
            if (!e.active || e.sourceId == 0) {
                if (!pool.allocate(e)) continue; // Pool full
                // Set immediate gain (no fade-in for triggered sounds)
                e.currentGain = e.targetGain;
                e.fadeProgress = 1.0f;
            }

            // Generate unique buffer
            int bufferId = generateTriggeredBuffer(e);
            if (bufferId == 0) {
                // No buffer generated (unsupported category like BAT) — release the slot
                if (e.active && e.sourceId != 0) {
                    pool.deallocate(e);
                }
                continue;
            }

<<<<<<< ours
<<<<<<< ours
            // Clean up old buffer if any (but never delete pooled sample buffers)
            int oldBuffer = AL10.alGetSourcei(e.sourceId, AL10.AL_BUFFER);
            AL10.alSourceStop(e.sourceId);
            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, 0);
            if (oldBuffer != 0 && !samplePoolLoader.isPooledBuffer(oldBuffer)) {
=======
            // Clean up old buffer if any
            int oldBuffer = AL10.alGetSourcei(e.sourceId, AL10.AL_BUFFER);
            AL10.alSourceStop(e.sourceId);
            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, 0);
            if (oldBuffer != 0) {
>>>>>>> theirs
=======
            // Clean up old buffer if any (but never delete pooled sample buffers)
            int oldBuffer = AL10.alGetSourcei(e.sourceId, AL10.AL_BUFFER);
            AL10.alSourceStop(e.sourceId);
            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, 0);
            if (oldBuffer != 0 && !samplePoolLoader.isPooledBuffer(oldBuffer)) {
>>>>>>> theirs
                AL10.alDeleteBuffers(oldBuffer);
            }

            // Bind new buffer and play
            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, bufferId);
            AL10.alSourcei(e.sourceId, AL10.AL_LOOPING, AL10.AL_FALSE);

            if (e.category == EmitterCategory.BIRD) {
<<<<<<< ours
<<<<<<< ours
=======
>>>>>>> theirs
                // Full 8-species pitch spread + per-call randomization
                float pitchBase = 0.75f + (e.speciesVariant * 0.06f); // 0.75-1.17 across 8 species
                float pitchJitter = 0.96f + triggeredRng.nextFloat() * 0.08f; // ±4% per call
                e.pitch = pitchBase * pitchJitter;
<<<<<<< ours
            }

            // Per-play pitch and gain variation for sample-based emitter categories.
            // Pitch: ±5% uniform spread prevents mechanical repetition across plays.
            // Gain: ±2 dB (converted from dB to linear) adds natural loudness variation.
            if (e.category == EmitterCategory.INSECT || e.category == EmitterCategory.FROG
                    || e.category == EmitterCategory.WATER_DRIP || e.category == EmitterCategory.WATER_RAIN
                    || e.category == EmitterCategory.WATER_STILL) {
                float pitchVar = 0.95f + triggeredRng.nextFloat() * 0.10f;  // ±5%
                float gainVar = (float) Math.pow(10.0, (-2.0 + triggeredRng.nextFloat() * 4.0) / 20.0);  // ±2 dB
                e.pitch = pitchVar;
                e.targetGain *= gainVar;
=======
                e.pitch = 0.85f + (e.speciesVariant & 3) * 0.1f;
>>>>>>> theirs
=======
>>>>>>> theirs
            }

            // Per-play pitch and gain variation for sample-based emitter categories.
            // Pitch: ±5% uniform spread prevents mechanical repetition across plays.
            // Gain: ±2 dB (converted from dB to linear) adds natural loudness variation.
            if (e.category == EmitterCategory.INSECT || e.category == EmitterCategory.FROG
                    || e.category == EmitterCategory.WATER_DRIP || e.category == EmitterCategory.WATER_RAIN
                    || e.category == EmitterCategory.WATER_STILL) {
                float pitchVar = 0.95f + triggeredRng.nextFloat() * 0.10f;  // ±5%
                float gainVar = (float) Math.pow(10.0, (-2.0 + triggeredRng.nextFloat() * 4.0) / 20.0);  // ±2 dB
                e.pitch = pitchVar;
                e.targetGain *= gainVar;
            }

            e.applyToOpenAL(masterGain);
            AL10.alSourcePlay(e.sourceId);
            e.lastCallTick = currentTick;
        }
    }

    /**
     * Rotates sample buffers on continuous emitters that use sample pools (e.g. WATER_FLOW).
     * When a one-shot buffer finishes (AL_STOPPED), picks a new random sample and replays.
     */
    private void tickContinuousSampleSwap(Random rng) {
        for (Emitter e : emittersByPos.values()) {
            if (e.category != EmitterCategory.WATER_FLOW) continue;
            if (e.sourceId == 0) continue;
            int state = AL10.alGetSourcei(e.sourceId, AL10.AL_SOURCE_STATE);
            if (state == AL10.AL_STOPPED) {
                int newBuffer = samplePoolLoader.getBuffer(
                    SampleSubcategory.WATER_FLOW_SAMPLE, e.sampleHistory, rng
                );
                if (newBuffer != 0) {
                    AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, newBuffer);
                    AL10.alSourcePlay(e.sourceId);
                }
            }
        }
    }

    /**
     * Generates a unique procedural audio buffer for a triggered emitter.
     * Each invocation produces distinct audio due to RNG variation and
     * condition-dependent parameters.
     *
     * @return OpenAL buffer ID, or 0 if the category is not supported
     */
    private int generateTriggeredBuffer(Emitter e) {
        int sampleCount;
        float[] samples;

        switch (e.category) {
            case BIRD -> {
                sampleCount = SAMPLE_RATE * (1 + triggeredRng.nextInt(2)); // 1-3 sec
                samples = new float[sampleCount];
                bufferFactory.generateBirdCall(samples, e.speciesVariant, triggeredRng);
            }
            case INSECT -> {
                return samplePoolLoader.getBuffer(e.subcategory, e.sampleHistory, triggeredRng);
            }
            case FROG -> {
                return samplePoolLoader.getBuffer(e.subcategory, e.sampleHistory, triggeredRng);
            }
            case WATER_DRIP -> {
                return samplePoolLoader.getBuffer(SampleSubcategory.WATER_DRIP_SAMPLE, e.sampleHistory, triggeredRng);
            }
            case WATER_RAIN -> {
                return samplePoolLoader.getBuffer(SampleSubcategory.WATER_RAIN_SAMPLE, e.sampleHistory, triggeredRng);
            }
            case WATER_STILL -> {
                return samplePoolLoader.getBuffer(SampleSubcategory.WATER_STILL, e.sampleHistory, triggeredRng);
            }
            case CAVE_AMBIENT -> {
                sampleCount = SAMPLE_RATE * (4 + triggeredRng.nextInt(2)); // 4-6 sec
                float roomSize = conditions != null ? Math.max(2f, conditions.roomSize()) : 10f;
                samples = new float[sampleCount];
                bufferFactory.generateCaveAmbient(samples, triggeredRng, roomSize, sampleCount);
            }
            case MECHANICAL -> {
                sampleCount = SAMPLE_RATE * (3 + triggeredRng.nextInt(2)); // 3-5 sec
                samples = new float[sampleCount];
                bufferFactory.generateFireCrackle(samples, triggeredRng, sampleCount);
            }
            default -> {
                return 0;
            }
        }

        return bufferFactory.createTriggeredBuffer(samples, sampleCount);
=======
        // Allocate sources for emitters that need them
        allocateNewEmitters();

        // Tick pool (smooth parameters, handle fades, recycle)
        pool.tick(masterGain, currentTick);
>>>>>>> theirs
    }

    /**
     * Reconciles scanner results with the current emitter map.
     * Adds new candidates, removes emitters no longer in scan results.
     * Density parameter controls how aggressively we prune.
     */
    private void reconcile(List<EmitterScanner.EmitterCandidate> candidates,
<<<<<<< ours
<<<<<<< ours
                           float playerX, float playerY, float playerZ,
                           EnvironmentConditions conditions) {
=======
                           float playerX, float playerY, float playerZ) {
>>>>>>> theirs
=======
                           float playerX, float playerY, float playerZ,
                           EnvironmentConditions conditions) {
>>>>>>> theirs
        Set<Long> foundKeys = new HashSet<>();

        for (EmitterScanner.EmitterCandidate c : candidates) {
            long key = posKey(c.x(), c.y(), c.z());
            foundKeys.add(key);

            if (!emittersByPos.containsKey(key)) {
                // Density-based LOD: skip some emitters when density < 1.0
                float dx = c.x() + 0.5f - playerX;
                float dy = c.y() + 0.5f - playerY;
                float dz = c.z() + 0.5f - playerZ;
                float dist = (float) Math.sqrt(dx * dx + dy * dy + dz * dz);

                // Beyond half-range, apply density-based thinning
                float halfRange = c.category().maxRange * 0.5f;
                if (dist > halfRange && density < 1.0f) {
                    int hash = (c.x() * 73 + c.z() * 37 + c.y() * 11) & 0xFF;
                    float threshold = density * 255f;
                    if (hash > threshold) {
                        continue;
                    }
                }

                Emitter emitter = new Emitter(c.category(), c.x(), c.y(), c.z());
<<<<<<< ours
<<<<<<< ours
                emitter.subcategory = assignSubcategory(c.category(), conditions, triggeredRng);
=======
>>>>>>> theirs
=======
                emitter.subcategory = assignSubcategory(c.category(), conditions, triggeredRng);
>>>>>>> theirs
                emittersByPos.put(key, emitter);
            }
        }

        // Remove emitters that are no longer in the scan
        emittersByPos.entrySet().removeIf(entry -> {
            if (!foundKeys.contains(entry.getKey())) {
                Emitter e = entry.getValue();
                if (e.active) {
                    pool.deallocate(e);
                }
<<<<<<< ours
                scheduler.remove(e);
=======
>>>>>>> theirs
                return true;
            }
            return false;
        });
    }

    /**
<<<<<<< ours
<<<<<<< ours
=======
>>>>>>> theirs
     * Assigns a sample subcategory for emitters that use sample pools.
     * Uses biome conditions and randomness for species diversity.
     *
     * @return the assigned subcategory, or null for categories that don't use samples
     */
    private SampleSubcategory assignSubcategory(EmitterCategory category, EnvironmentConditions conditions, Random rng) {
        return switch (category) {
            case INSECT -> {
                float r = rng.nextFloat();
                if (r < 0.50f) yield SampleSubcategory.CRICKET;
                if (r < 0.70f) yield SampleSubcategory.CICADA;
                if (r < 0.85f) yield SampleSubcategory.KATYDID;
                yield SampleSubcategory.GENERIC_NIGHT;
            }
            case FROG -> {
                if (conditions != null && conditions.isSwamp()) yield SampleSubcategory.CHORUS_FROG;
                if (conditions != null && conditions.isForest()) {
                    yield rng.nextBoolean() ? SampleSubcategory.TREE_FROG : SampleSubcategory.SPRING_PEEPER;
                }
                yield SampleSubcategory.BULLFROG;
            }
            case WATER_STILL -> SampleSubcategory.WATER_STILL;
            default -> null;
        };
    }

    /**
<<<<<<< ours
=======
>>>>>>> theirs
=======
>>>>>>> theirs
     * Removes emitters that are beyond their category's max range.
     */
    private void cull(float playerX, float playerY, float playerZ) {
        emittersByPos.entrySet().removeIf(entry -> {
            Emitter e = entry.getValue();
            float dx = e.blockX + 0.5f - playerX;
            float dy = e.blockY + 0.5f - playerY;
            float dz = e.blockZ + 0.5f - playerZ;
            float dist = (float) Math.sqrt(dx * dx + dy * dy + dz * dz);
            e.distanceToListener = dist;

            if (dist > e.category.maxRange) {
                if (e.active) {
                    pool.deallocate(e);
                }
<<<<<<< ours
                scheduler.remove(e);
=======
>>>>>>> theirs
                return true;
            }
            return false;
        });
    }

    /**
     * Computes target gain for each tracked emitter based on distance,
<<<<<<< ours
     * category, wind exposure, environment profile, and conditions.
     * When conditions are available, uses condition-aware modulation for
     * fauna, weather, and time-of-day effects.
=======
     * category, wind exposure, and environment profile.
>>>>>>> theirs
     */
    private void updateGains(float playerX, float playerY, float playerZ,
                             EnvironmentProfile profile) {
        float windExposure = profile.windExposure();
<<<<<<< ours
        EnvironmentConditions cond = this.conditions;

        for (Emitter e : emittersByPos.values()) {
            // distanceToListener already computed by cull() earlier in the tick
            float dist = e.distanceToListener;
=======

        for (Emitter e : emittersByPos.values()) {
            float dx = e.blockX + 0.5f - playerX;
            float dy = e.blockY + 0.5f - playerY;
            float dz = e.blockZ + 0.5f - playerZ;
            float dist = (float) Math.sqrt(dx * dx + dy * dy + dz * dz);
            e.distanceToListener = dist;
>>>>>>> theirs

            float maxRange = e.category.maxRange;
            if (dist > maxRange) {
                e.targetGain = 0f;
                continue;
            }

            // Distance attenuation: linear rolloff
            float distGain = 1.0f - (dist / maxRange);
            distGain = Math.max(0f, Math.min(1f, distGain));

<<<<<<< ours
            // Category-specific gain modulation — condition-aware when available
            float categoryGain;
            if (cond != null) {
                // Night: winds calm due to nocturnal boundary layer decoupling.
                // Surface winds drop ~55% after sunset. This unmasks nocturnal fauna.
                float nightCalm = 1.0f - (1.0f - cond.daylight()) * 0.55f;
                categoryGain = switch (e.category) {
                    case WIND_LEAF -> windExposure * 0.55f * nightCalm;
                    case WIND_GRASS -> windExposure * 0.45f * nightCalm;
                    case WIND_WHISTLE -> windExposure * windExposure * 0.3f;
                    case WATER_FLOW -> 0.55f;
                    case WATER_DRIP -> 0.50f;
                    case WATER_RAIN -> cond.isRaining() ? 0.45f : 0.0f;
                    case WATER_STILL -> {
                        float base = 0.25f;
                        if (cond.isRaining()) base *= 1.4f;
                        yield base;
                    }
                    case LAVA -> 0.4f;
                    case CAVE_AMBIENT -> {
                        // Use enclosure, NOT daylight — caves don't know about time of day.
                        // Buffer is reshaped for transient events: quiet brown noise base
                        // (0.04) with loud drip transients (0.50-0.80). Balanced gain
                        // so drips are audible without swamping spatial decorrelation.
                        float enclosureBoost = cond.enclosure() > 0.5f ? 1.0f : 0.5f;
                        yield 0.20f * enclosureBoost;
                    }
                    case CAVE_DRONE -> {
                        // Continuous cave room tone — scales with enclosure.
                        // Must stay well below the spatial field (decorrelation engine)
                        // to keep IC < 0.7. Cave drones are correlated across sources,
                        // so they collapse the stereo image if too loud.
                        float encScale = Math.max(0f, (cond.enclosure() - 0.3f) / 0.7f);
                        yield 0.03f * encScale;
                    }
                    case MECHANICAL -> 0.35f;
                    case BIRD -> {
                        // Suppress in highly enclosed spaces (sealed rooms/caves)
                        // Only kicks in above enclosure 0.6 — forests with canopy stay unaffected
                        float outdoorGate = cond.enclosure() > 0.6f
                                ? Math.max(0f, 1.0f - (cond.enclosure() - 0.6f) * 2.5f) : 1.0f;
                        float timeGate = cond.daylight() > 0.15f ? 1.0f : 0.0f;
<<<<<<< ours
                        float dawnBoost = 1.0f + cond.dawnChorus() * 2.5f;
                        float forestBoost = cond.isForest() ? 1.3f : 1.0f;
                        yield Math.min(1.0f, 0.65f * timeGate * dawnBoost * forestBoost * outdoorGate);
=======
                        float dawnBoost = 1.0f + cond.dawnChorus() * 1.5f;
                        float forestBoost = cond.isForest() ? 1.3f : 1.0f;
                        yield 0.4f * timeGate * dawnBoost * forestBoost;
>>>>>>> theirs
                    }
                    case INSECT -> {
                        float outdoorGate = cond.enclosure() > 0.6f
                                ? Math.max(0f, 1.0f - (cond.enclosure() - 0.6f) * 2.5f) : 1.0f;
                        float nightBoost = 1.0f + (1.0f - cond.daylight()) * 1.0f;
                        float tempGate = Math.max(0f, (cond.temperature() - 0.15f) / 0.5f);
                        yield Math.min(0.70f, 0.35f * nightBoost * tempGate * outdoorGate);
                    }
                    case FROG -> {
                        float outdoorGate = cond.enclosure() > 0.6f
                                ? Math.max(0f, 1.0f - (cond.enclosure() - 0.6f) * 2.5f) : 1.0f;
                        float duskPeak = cond.duskFactor();
                        float nightActive = cond.daylight() < 0.3f ? 1.0f : 0.2f;
                        float timeModulation = Math.max(nightActive, duskPeak);
                        float swampBoost = cond.isSwamp() ? 1.5f : 1.0f;
                        yield 0.45f * timeModulation * swampBoost * outdoorGate;
                    }
                    case BAT -> 0.20f;
                };
            } else {
                // Fallback: profile-only gains (no conditions available)
                categoryGain = switch (e.category) {
                    case WIND_LEAF -> windExposure * 0.55f;
                    case WIND_GRASS -> windExposure * 0.45f;
                    case WIND_WHISTLE -> windExposure * windExposure * 0.3f;
                    case WATER_FLOW -> 0.55f;
                    case WATER_DRIP -> 0.50f;
                    case WATER_RAIN -> windExposure * 0.35f;
                    case WATER_STILL -> 0.25f;
                    case LAVA -> 0.4f;
                    case CAVE_AMBIENT -> 0.20f;
                    case CAVE_DRONE -> 0.03f;
                    case MECHANICAL -> 0.35f;
                    case BIRD -> windExposure * 0.5f;
                    case INSECT -> 0.35f;
                    case FROG -> 0.35f;
                    case BAT -> 0.20f;
                };
            }

            // Per-category enable/disable
            if (Boolean.FALSE.equals(categoryEnabled.get(e.category))) {
                categoryGain = 0f;
            }
            // Fauna volume multiplier
            if (isFaunaCategory(e.category)) {
                categoryGain *= faunaVolume;
            }

            e.targetGain = distGain * categoryGain;

            // Underwater: mute wind/fauna, heavily attenuate everything else
            if (underwater) {
                boolean isAerial = e.category == EmitterCategory.WIND_LEAF
                        || e.category == EmitterCategory.WIND_GRASS
                        || e.category == EmitterCategory.WIND_WHISTLE
                        || isFaunaCategory(e.category);
                e.targetGain *= isAerial ? 0f : 0.15f; // -16 dB underwater
            }

            // HF filter: more distance = darker sound (+ underwater darkening)
            float hfRolloff = 1.0f - (dist / maxRange) * 0.5f;
            e.targetFilterGainHF = Math.max(0.2f, Math.min(1f, hfRolloff));
            if (underwater) {
                // Aggressive LPF: water absorbs ~3.5 dB/m at 10kHz vs ~0.003 dB/m
                // at 100 Hz. OpenAL's single-pole lowpass with GAINHF=0.01 puts
                // the -3dB point well below 500 Hz, matching the heavily damped
                // underwater spectrum perceived by divers.
                e.targetFilterGainHF *= 0.01f; // ~40 dB HF cut

                // Pitch shift down ~1.3 octaves: water's higher speed of sound
                // (1500 m/s vs 343 m/s) and impedance mismatch cause perceived
                // frequency shift. This moves the WATER_FLOW 200-800 Hz mid-band
                // down to 80-320 Hz, dramatically lowering the spectral centroid.
                e.pitch = 0.4f;
            } else {
                // Reset pitch for non-underwater (birds set their own pitch later)
                if (!e.category.sampleBased) {
                    e.pitch = 1.0f;
                }
            }
=======
            // Category-specific gain modulation
            float categoryGain = switch (e.category) {
                case WIND_LEAF -> windExposure * 0.6f;
                case WIND_GRASS -> windExposure * 0.4f;
                case WIND_WHISTLE -> windExposure * windExposure * 0.3f;
                case WATER_FLOW -> 0.2f;
                case WATER_DRIP -> 0.15f;
                case WATER_RAIN -> windExposure * 0.25f;
                case LAVA -> 0.3f;
                case CAVE_AMBIENT -> 0.08f;
                case MECHANICAL -> 0.2f;
                case BIRD -> windExposure * 0.3f;
                case INSECT -> 0.1f;
                case FROG -> 0.15f;
                case BAT -> 0.12f;
            };

            e.targetGain = distGain * categoryGain;

            // Underwater: mute wind/fauna, heavily attenuate everything else
            if (underwater) {
                boolean isAerial = e.category == EmitterCategory.WIND_LEAF
                        || e.category == EmitterCategory.WIND_GRASS
                        || e.category == EmitterCategory.WIND_WHISTLE
                        || isFaunaCategory(e.category);
                e.targetGain *= isAerial ? 0f : 0.15f;
            }

            // HF filter: more distance = darker sound (+ underwater darkening)
            float hfRolloff = 1.0f - (dist / maxRange) * 0.5f;
            e.targetFilterGainHF = Math.max(0.2f, Math.min(1f, hfRolloff));
<<<<<<< ours
>>>>>>> theirs
=======
            if (underwater) {
                e.targetFilterGainHF *= 0.3f; // Heavy LPF underwater
            }
>>>>>>> theirs
        }
    }

    /**
<<<<<<< ours
     * Returns true if the given category is a fauna sound (affected by
     * faunaEnabled and faunaVolume settings).
     */
    private static boolean isFaunaCategory(EmitterCategory category) {
        return category == EmitterCategory.BIRD
                || category == EmitterCategory.INSECT
                || category == EmitterCategory.FROG
                || category == EmitterCategory.BAT;
    }

    /**
     * Allocates OpenAL sources and binds procedural buffers for
     * emitters that are tracked but not yet active.
     * Enforces per-category caps to prevent any single category from flooding the pool.
     */
    private void allocateNewEmitters() {
        // Count current active emitters per category
        Map<EmitterCategory, Integer> activeCounts = new EnumMap<>(EmitterCategory.class);
        for (Emitter e : pool.getActiveEmitters()) {
            if (!e.category.sampleBased) {
                activeCounts.merge(e.category, 1, Integer::sum);
            }
        }

        for (Emitter e : emittersByPos.values()) {
            if (e.active || e.targetGain < 0.001f) continue;
            if (e.category.sampleBased) continue; // Triggered emitters allocate on-demand

            // Enforce per-category cap
            int maxForCategory = MAX_CONTINUOUS_PER_CATEGORY.getOrDefault(e.category, 4);
            int currentCount = activeCounts.getOrDefault(e.category, 0);
            if (currentCount >= maxForCategory) continue;

            if (pool.allocate(e)) {
                bindBuffer(e);
                activeCounts.merge(e.category, 1, Integer::sum);
=======
     * Allocates OpenAL sources and binds procedural buffers for
     * emitters that are tracked but not yet active.
     */
    private void allocateNewEmitters() {
        for (Emitter e : emittersByPos.values()) {
            if (e.active || e.targetGain < 0.001f) continue;
            if (e.category.sampleBased) continue; // Triggered emitters allocate on-demand

            if (pool.allocate(e)) {
                bindBuffer(e);
>>>>>>> theirs
            }
        }
    }

    /**
     * Loads a procedural buffer onto the emitter's source, sets it to
     * loop, and applies a staggered start offset to avoid phase alignment.
     */
    private void bindBuffer(Emitter e) {
        if (e.sourceId == 0) return;

        if (e.category.sampleBased) {
            // Sample-based emitters will be triggered separately
            return;
        }

<<<<<<< ours
<<<<<<< ours
=======
>>>>>>> theirs
        int bufferId;
        if (e.category == EmitterCategory.WATER_FLOW) {
            // WATER_FLOW uses sample pool: one-shot playback with rotation via tickContinuousSampleSwap
            bufferId = samplePoolLoader.getBuffer(SampleSubcategory.WATER_FLOW_SAMPLE, e.sampleHistory, triggeredRng);
            if (bufferId == 0) return;
<<<<<<< ours

            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, bufferId);
            AL10.alSourcei(e.sourceId, AL10.AL_LOOPING, AL10.AL_FALSE);
        } else {
            // Procedural continuous emitters: loop a generated buffer
            int variant = Math.abs(e.blockX * 73 + e.blockZ * 37 + e.blockY * 11) % 4;
            bufferId = bufferFactory.getBuffer(e.category, variant);
            if (bufferId == 0) return;

            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, bufferId);
            AL10.alSourcei(e.sourceId, AL10.AL_LOOPING, AL10.AL_TRUE);
        }
=======
        int bufferId = bufferFactory.getBuffer(e.category);
        if (bufferId == 0) return;

        AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, bufferId);
        AL10.alSourcei(e.sourceId, AL10.AL_LOOPING, AL10.AL_TRUE);
>>>>>>> theirs
=======

            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, bufferId);
            AL10.alSourcei(e.sourceId, AL10.AL_LOOPING, AL10.AL_FALSE);
        } else {
            // Procedural continuous emitters: loop a generated buffer
            int variant = Math.abs(e.blockX * 73 + e.blockZ * 37 + e.blockY * 11) % 4;
            bufferId = bufferFactory.getBuffer(e.category, variant);
            if (bufferId == 0) return;

            AL10.alSourcei(e.sourceId, AL10.AL_BUFFER, bufferId);
            AL10.alSourcei(e.sourceId, AL10.AL_LOOPING, AL10.AL_TRUE);
        }
>>>>>>> theirs

        // Stagger start offset to avoid phase correlation between emitters
        int bufferSize = AL10.alGetBufferi(bufferId, AL10.AL_SIZE);
        int channels = AL10.alGetBufferi(bufferId, AL10.AL_CHANNELS);
        int bits = AL10.alGetBufferi(bufferId, AL10.AL_BITS);
        int bytesPerSample = (bits / 8) * channels;
        if (bytesPerSample > 0 && bufferSize > 0) {
            int totalSamples = bufferSize / bytesPerSample;
            // Hash position to get deterministic but varied offset
            int hash = Math.abs(e.blockX * 73 + e.blockZ * 37 + e.blockY * 11);
            int offset = hash % totalSamples;
            AL10.alSourcei(e.sourceId, AL11.AL_SAMPLE_OFFSET, offset);
        }

        AL10.alSourcePlay(e.sourceId);
    }

    // ── Configuration ────────────────────────────────────────────────

    public void setEnabled(boolean enabled) {
        if (!enabled && this.enabled) {
            silenceAll();
        }
        this.enabled = enabled;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setMasterGain(float gain) {
        this.masterGain = gain;
    }

<<<<<<< ours
    /**
     * Forces an immediate rescan on the next tick. Call after teleportation
     * to avoid stale emitter data causing silence gaps.
     */
    public void forceRescan() {
        ticksSinceRescan = RESCAN_INTERVAL_TICKS;
        scanInProgress = false;
    }

=======
>>>>>>> theirs
    public void setDensity(float density) {
        this.density = Math.max(0.25f, Math.min(1.0f, density));
    }

<<<<<<< ours
    public void setCategoryEnabled(EmitterCategory category, boolean enabled) {
        categoryEnabled.put(category, enabled);
    }

    public void setFaunaEnabled(boolean enabled) {
        categoryEnabled.put(EmitterCategory.BIRD, enabled);
        categoryEnabled.put(EmitterCategory.INSECT, enabled);
        categoryEnabled.put(EmitterCategory.FROG, enabled);
        categoryEnabled.put(EmitterCategory.BAT, enabled);
    }

    public void setFaunaVolume(float volume) {
        this.faunaVolume = volume;
    }

    public EnvironmentConditions getConditions() {
        return conditions;
    }

=======
>>>>>>> theirs
    // ── Lifecycle ────────────────────────────────────────────────────

    public void silenceAll() {
        pool.silenceAll();
    }

    public void shutdown() {
        pool.shutdown();
        bufferFactory.shutdown();
<<<<<<< ours
<<<<<<< ours
=======
>>>>>>> theirs
        samplePoolLoader.shutdown();
        emittersByPos.clear();
        scheduler.clear();
=======
        emittersByPos.clear();
>>>>>>> theirs
        Loggers.log("EmitterManager: shut down");
    }

    // ── Diagnostics ──────────────────────────────────────────────────

    public int getActiveCount() {
        return pool.getActiveCount();
    }

    public int getTotalTracked() {
        return emittersByPos.size();
    }

    /**
     * Returns an estimate of the total scene audio energy from all active emitters.
     */
    public float getSceneEnergy() {
        float energy = 0f;
        for (Emitter e : pool.getActiveEmitters()) {
            energy += e.currentGain * e.currentGain;
        }
        return energy;
    }

    public EmitterPool getPool() {
        return pool;
    }

    /**
     * Packs block coordinates into a single long key for the emitter map.
     * Uses BlockPos.asLong() layout: x in high bits, z in mid, y in low.
     */
    private static long posKey(int x, int y, int z) {
        return BlockPos.asLong(x, y, z);
    }
}
